name: Use Central Workflow

on:
  workflow_dispatch:

jobs:
  invoke-central-workflow:
    runs-on: ubuntu-latest
    name: Call composite workflow
    steps:
        - uses: chickendining/simple-workflow-repo/.github/actions/sync@main
          with:
            caller_repo: "chickendining/another_repo"
